services:

  db:
    image: postgres:15.4
    container_name: db
    env_file:
      - config/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - web_net
    restart: on-failure

  web:
    build: .
    container_name: web
    command: sh -c "make all && make runprod"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    env_file:
      - config/.env
    depends_on:
      - db
    links:
      - db:db
    networks:
      - web_net

    restart: always

  nginx:
    image: nginx:stable
    container_name: nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - web
    networks:
      - web_net
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/static
    restart: on-failure

volumes:
  postgres_data:

networks:
    web_net:
      driver: bridge
