name: iPortfolio
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.7
      - name: Install Dependencies
        run: |
          make -C ./src/ install
      - name: Lint with Pylint
        run: |
          make -C ./src/ lint
      - name: Format Code
        run: |
          make -C ./src/ format
      - name: Make migrations & migrate
        run: |
          make -C ./src/ makemigrations migrate
          
