name: iPortfolio
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.5
      - name: Install Dependencies
        run: |
          make install
      - name: Lint with Pylint
        run: |
          make lint
      - name: Format Code
        run: |
          make format
      - name: Make migrations & migrate
        run: |
          make makemigrations && make migrate
          
